package com.projectkinetile.physicsengine.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.time.Instant;
import java.util.UUID;

/**
 * Persistent record of one tile compression event and its evaluated hardware activation outcome.
 *
 * <p>Location and manufacturer are resolved via {@link TileEntity} joins — not denormalized here.
 */
@Entity
@Table(
    name = "tile_compression_events",
    uniqueConstraints = @UniqueConstraint(name = "uq_tce_event_id", columnNames = "event_id"),
    indexes = {
      @Index(name = "idx_tce_tile_id_event_timestamp", columnList = "tile_id, event_timestamp"),
      @Index(name = "idx_tce_event_timestamp", columnList = "event_timestamp"),
      @Index(name = "idx_tce_activation", columnList = "activation_successful")
    })
public class TileCompressionEventEntity {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @Column(name = "event_id", nullable = false)
  private String eventId;

  @Convert(converter = TileCompressionEventTypeConverter.class)
  @Column(name = "event_type", nullable = false)
  private TileCompressionEventType eventType;

  @Column(name = "tile_id", nullable = false, insertable = false, updatable = false)
  private UUID tileId;

  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  @JoinColumn(name = "tile_id", referencedColumnName = "tile_id", nullable = false)
  private TileEntity tile;

  @Column(name = "mass_kg", nullable = false)
  private double massKg;

  @Column(name = "impact_multiplier", nullable = false)
  private double impactMultiplier;

  @Column(name = "calculated_force_newtons", nullable = false)
  private double calculatedForceNewtons;

  @Column(name = "calculated_energy_joules", nullable = false)
  private double calculatedEnergyJoules;

  @Column(name = "activation_successful", nullable = false)
  private boolean activationSuccessful;

  @Column(name = "event_timestamp", nullable = false, columnDefinition = "timestamp with time zone")
  private Instant eventTimestamp;

  @JsonIgnore
  @Column(name = "created_at", columnDefinition = "timestamp with time zone")
  private Instant createdAt;

  @JsonIgnore
  @Column(name = "updated_at", columnDefinition = "timestamp with time zone")
  private Instant updatedAt;

  /** Required by JPA. */
  public TileCompressionEventEntity() {}

  /**
   * Creates a row for one evaluated compression event. {@code id} is generated by the database.
   */
  public TileCompressionEventEntity(
      String eventId,
      TileCompressionEventType eventType,
      TileEntity tile,
      double massKg,
      double impactMultiplier,
      double calculatedForceNewtons,
      double calculatedEnergyJoules,
      boolean activationSuccessful,
      Instant eventTimestamp,
      Instant createdAt,
      Instant updatedAt) {
    this.eventId = eventId;
    this.eventType = eventType;
    this.tile = tile;
    this.tileId = tile != null ? tile.getTileId() : null;
    this.massKg = massKg;
    this.impactMultiplier = impactMultiplier;
    this.calculatedForceNewtons = calculatedForceNewtons;
    this.calculatedEnergyJoules = calculatedEnergyJoules;
    this.activationSuccessful = activationSuccessful;
    this.eventTimestamp = eventTimestamp;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getEventId() {
    return eventId;
  }

  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  public TileCompressionEventType getEventType() {
    return eventType;
  }

  public void setEventType(TileCompressionEventType eventType) {
    this.eventType = eventType;
  }

  public UUID getTileId() {
    return tileId;
  }

  public TileEntity getTile() {
    return tile;
  }

  public void setTile(TileEntity tile) {
    this.tile = tile;
    this.tileId = tile != null ? tile.getTileId() : null;
  }

  public double getMassKg() {
    return massKg;
  }

  public void setMassKg(double massKg) {
    this.massKg = massKg;
  }

  public double getImpactMultiplier() {
    return impactMultiplier;
  }

  public void setImpactMultiplier(double impactMultiplier) {
    this.impactMultiplier = impactMultiplier;
  }

  public double getCalculatedForceNewtons() {
    return calculatedForceNewtons;
  }

  public void setCalculatedForceNewtons(double calculatedForceNewtons) {
    this.calculatedForceNewtons = calculatedForceNewtons;
  }

  public double getCalculatedEnergyJoules() {
    return calculatedEnergyJoules;
  }

  public void setCalculatedEnergyJoules(double calculatedEnergyJoules) {
    this.calculatedEnergyJoules = calculatedEnergyJoules;
  }

  public boolean isActivationSuccessful() {
    return activationSuccessful;
  }

  public void setActivationSuccessful(boolean activationSuccessful) {
    this.activationSuccessful = activationSuccessful;
  }

  public Instant getEventTimestamp() {
    return eventTimestamp;
  }

  public void setEventTimestamp(Instant eventTimestamp) {
    this.eventTimestamp = eventTimestamp;
  }

  public Instant getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Instant createdAt) {
    this.createdAt = createdAt;
  }

  public Instant getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(Instant updatedAt) {
    this.updatedAt = updatedAt;
  }
}
